DROP DATABASE IF EXISTS d4skt5hlo3di1vql;
CREATE DATABASE d4skt5hlo3di1vql;
USE d4skt5hlo3di1vql;

CREATE TABLE burgers (
  id INTEGER AUTO_INCREMENT NOT NULL,
  burger_name VARCHAR(255),
  devoured BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (id)
);